# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1

##### Ecuacion
$$p = (I-A)^{-1}d = Ld$$

Si $d = 0$ entonce $p = 0$  ??


### Consigna 2

In [4]:
from funciones import inversaLU, calcularPLU, solve_LU, calcularLU, inversaLUpivot
import numpy as np

array([[ 0.,  1.,  0., -1.],
       [ 0.,  0., -4.,  0.],
       [-2.,  1.,  1.,  2.],
       [ 3., -3.,  0.,  2.]])

---

### Consigna 3

In [6]:
A = np.array([[0.3, 0.0, 0.1],[0.05, 1.0, 0.2],[0.1, 0.15, 0.1]])
d = np.array([100,100,300])
rows,cols = A.shape
id = np.eye(rows, cols)
i_A = id - A
L, U, P= calcularPLU(i_A)
leontief = inversaLUpivot(L,U,P)

p = leontief @ d
p

array([   64.03940887, -5305.41871921,  -551.72413793])

a) Como el producto 2 necesita 1 producto 2 para uno, mas los gasto de los demas productos nunca llega a satisfacer la demanda por ende so produccion total es negativa


---

### Consigna 4

In [10]:
delta_d = d + np.array([0,0,1])
delta_p = leontief @ delta_d
delta_p

array([   64.03940887, -5312.08538588,  -551.72413793])

---

### Consigna 5

In [ ]:
Z = np.array([[350, 0, 0],[50, 250, 150],[200, 150, 550]])
rows, cols = Z.shape
P = np.array([[1000,0,0],[0,500,0],[0,0,1000]])

A = Z @ inversaLU(*calcularLU(P))
A

---
### Consigna 6