# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1

##### Ecuacion
$$p = (I-A)^{-1}d = Ld$$

Si $d = 0$ entonce $p = 0$  ??

##### a) 
Cuando $ (I-A) $ es inversible la matriz de Leontief se puede calcular. En este caso la solucion al sistema 2 existe y es unica.

##### b) 
Cuando $ (I-A) $ es inversible pero el vector d = 0 tenemos una economia cerrada en donde para toda matriz de Leontief el valor de p va a ser 0.

##### c) 
Cuando $ (I-A) $ no es inversible significa que el sistema no tiene solucion unica o no tiene solucion.

##### d) 
Cuando $ (I-A) $ no es inversible y d = 0 el sistema se puede reducir a $ (I-A)p = 0 $ el cual posee soluciones no triviales por lo tanto hay soluciones infinitas que satisfacen la ecuacion.


### Consigna 2

In [1]:
from funciones import inversaLU, calcularPLU, solve_LU, calcularLU, inversaLUpivot
import numpy as np

[[ 0.  1.  0. -1.]
 [ 0.  0. -4.  0.]
 [-2.  1.  1.  2.]
 [ 3. -3.  0.  2.]]
[[ 1.     0.     0.     0.   ]
 [-0.     1.     0.     0.   ]
 [-0.     0.     1.     0.   ]
 [-1.5   -1.5   -0.375  1.   ]]
[[-2.   1.   1.   2. ]
 [ 0.   1.   0.  -1. ]
 [ 0.   0.  -4.   0. ]
 [ 0.   0.   0.   3.5]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
A permutada:
 [[-2.  1.  1.  2.]
 [ 0.  1.  0. -1.]
 [ 0.  0. -4.  0.]
 [ 3. -3.  0.  2.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
A permutada inversa: 
 [[ 0.14285714  1.14285714  0.03571429  0.42857143]
 [ 0.42857143  1.42857143  0.10714286  0.28571429]
 [-0.         -0.         -0.25       -0.        ]
 [ 0.42857143  0.42857143  0.10714286  0.28571429]]
A inversa: 
 [[ 1.14285714  0.03571429  0.14285714  0.42857143]
 [ 1.42857143  0.10714286  0.42857143  0.28571429]
 [ 0.         -0.25        0.          0.        ]
 [ 0.42857143  0.10714286  0.42857143  0.28571429]]
Leontief:
 [[ 1.14285714  0.03571429  0.142857

---

### Consigna 3

In [6]:
A = np.array([[0.3, 0.0, 0.1],[0.05, 1.0, 0.2],[0.1, 0.15, 0.1]])
d = np.array([100,100,300])
rows,cols = A.shape
id = np.eye(rows, cols)
i_A = id - A
L, U, P= calcularPLU(i_A)
leontief = inversaLUpivot(L,U,P)

p = leontief @ d
p

array([   64.03940887, -5305.41871921,  -551.72413793])

a) Como el producto 2 necesita 1 producto 2 para producirse uno, ademas de los gastos de los demas productos nunca llega a satisfacer la demanda por ende so produccion total es negativa (creo que aca no estamos viendo bien a la matriz de la demanda interna la cual deberia ser la matriz de leontief y no la matriz A, lo que me llama la atencion es que nos esta viniendo con valores negativos cuando la demanda deberia ser positiva?)


---

### Consigna 4

In [10]:
delta_d = d + np.array([0,0,1])
delta_p = leontief @ delta_d
delta_p

array([   64.03940887, -5312.08538588,  -551.72413793])

---

### Consigna 5

In [3]:
Z = np.array([[350, 0, 0],[50, 250, 150],[200, 150, 550]])
rows, cols = Z.shape
P = np.array([[1000,0,0],[0,500,0],[0,0,1000]])

A = Z @ inversaLU(*calcularLU(P))
i_A = np.eye(rows, cols) - A
leontief = inversaLUpivot(*calcularPLU(i_A))
print(A)
leontief 

[[0.35 0.   0.  ]
 [0.05 0.5  0.15]
 [0.2  0.3  0.55]]


array([[1.53846154, 0.        , 0.        ],
       [0.44871795, 2.5       , 0.83333333],
       [0.98290598, 1.66666667, 2.77777778]])

---
### Consigna 6

---
### Consigna 7

In [16]:
import pandas as pd

path = "matrizlatina2011_compressed_0.xlsx"
dataset = pd.read_excel(path, sheet_name=1)

<bound method NDFrame.head of     Country_iso3 Nosector                                             Sector  \
160          COL      s01                           Agriculture and forestry   
161          COL      s02                                Hunting and fishing   
162          COL      s03                      Mining and quarrying (energy)   
163          COL      s04                  Mining and quarrying (non-energy)   
164          COL      s05             Meat and meat products; dairy products   
165          COL      s06                           Wheat products and pasta   
166          COL      s07                            Sugar and confectionery   
167          COL      s08                               Other processed food   
168          COL      s09                                           Beverage   
169          COL      s10                                            Tobacco   
170          COL      s11                                           Textiles   
171       

In [19]:

COL = dataset[dataset["Country_iso3"] =="COL"]
BOL = dataset[dataset["Country_iso3"] =="BOL"]
COL.head()
BOL.head()

Country_iso3 Nosector                                  Sector     ARGs1  \
80          BOL      s01                Agriculture and forestry  0.483656   
81          BOL      s02                     Hunting and fishing  0.000000   
82          BOL      s03           Mining and quarrying (energy)  0.000091   
83          BOL      s04       Mining and quarrying (non-energy)  0.000000   
84          BOL      s05  Meat and meat products; dairy products  0.000000   

           ARGs2     ARGs3     ARGs4         ARGs5     ARGs6     ARGs7  ...  \
80  0.000000e+00  0.000000  0.000000  2.730346e-02  0.025187  0.005283  ...   
81  0.000000e+00  0.000000  0.000000  0.000000e+00  0.000000  0.000000  ...   
82  1.038337e-02  0.285460  0.048548  1.013565e-02  0.005844  0.001376  ...   
83  6.600000e-08  0.281683  0.036713  3.750000e-07  0.000021  0.000001  ...   
84  0.000000e+00  0.000000  0.000000  0.000000e+00  0.000000  0.000000  ...   

    EXP_MDV  EXP_NPL  EXP_TUR  EXP_PAK  EXP_LKA  EXP_CUB  EXP_SUR    EXP_ROW  \
80      0.0      0.0   0.0769      0.0      0.0      0.0      0.0   4.111023   
81      0.0      0.0   0.0000      0.0      0.0      0.0      0.0   0.000000   
82      0.0      0.0   0.0000      0.0      0.0      0.0      0.0   0.635127   
83      0.0      0.0   0.0000      0.0      0.0      0.0      0.0  74.974060   
84      0.0      0.0   0.0000      0.0      0.0      0.0      0.0   0.000000   

      Adjustment       Output  
80 -2.107575e+01  3487.321711  
81 -1.430000e-07     4.048915  
82 -1.708611e+03  4716.747980  
83  2.456311e+02  3646.153101  
84 -3.367134e-01  1265.894610  

[5 rows x 798 columns]