# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1

##### Ecuacion
$$p = (I-A)^{-1}d = Ld$$

Si $d = 0$ entonce $p = 0$  ??

##### a. Cuando $ (I-A) $ es inversible la matriz de Leontief se puede calcular. En este caso la solucion al sistema 2 existe y es unica.

##### b. Cuando $ (I-A) $ es inversible pero el vector d = 0 tenemos una economia cerrada en donde para toda matriz de Leontief el valor de p va a ser 0.

##### c. Cuando $ (I-A) $ no es inversible significa que el sistema no tiene solucion unica o no tiene solucion.

##### d. Cuando $ (I-A) $ no es inversible y d = 0 el sistema se puede reducir a $ (I-A)p = 0 $ el cual posee soluciones no triviales por lo tanto hay soluciones infinitas que satisfacen la ecuacion.


### Consigna 2

In [5]:
from funciones import inversaLU, calcularPLU, solve_LU, calcularLU, inversaLUpivot, calcular_coeficientes_tecnicos
import numpy as np

---

### Consigna 3

In [6]:
A = np.array([[0.3, 0.0, 0.1],[0.05, 1.0, 0.2],[0.1, 0.15, 0.1]])
d = np.array([100,100,300])
rows,cols = A.shape
id = np.eye(rows, cols)
i_A = id - A
L, U, P= calcularPLU(i_A)
leontief = inversaLUpivot(L,U,P)

p = leontief @ d
p

array([   64.03940887, -5305.41871921,  -551.72413793])

a) Como el producto 2 necesita 1 producto 2 para producirse uno, ademas de los gastos de los demas productos nunca llega a satisfacer la demanda por ende so produccion total es negativa (creo que aca no estamos viendo bien a la matriz de la demanda interna la cual deberia ser la matriz de leontief y no la matriz A, lo que me llama la atencion es que nos esta viniendo con valores negativos cuando la demanda deberia ser positiva?)


---

### Consigna 4

In [10]:
delta_d = d + np.array([0,0,1])
delta_p = leontief @ delta_d
delta_p

array([   64.03940887, -5312.08538588,  -551.72413793])

---

### Consigna 5

In [2]:
Z = np.array([[350, 0, 0],[50, 250, 150],[200, 150, 550]])
rows, cols = Z.shape
P = np.array([[1000,0,0],[0,500,0],[0,0,1000]])

A = calcular_coeficientes_tecnicos(Z,P)
i_A = np.eye(rows, cols) - A
leontief = inversaLUpivot(*calcularPLU(i_A))
print(A)
leontief 

[[0.35 0.   0.  ]
 [0.05 0.5  0.15]
 [0.2  0.3  0.55]]


array([[1.53846154, 0.        , 0.        ],
       [0.44871795, 2.5       , 0.83333333],
       [0.98290598, 1.66666667, 2.77777778]])

---
### Consigna 6

---
### Consigna 7

In [1]:
import pandas as pd

path = "matrizlatina2011_compressed_0.xlsx"
dataset = pd.read_excel(path, sheet_name=1)

b)

In [2]:

COL = dataset[dataset["Country_iso3"] =="COL"]
BOL = dataset[dataset["Country_iso3"] =="BOL"]

In [3]:
#Separamos los dataframes de cada pais 

bol_cols = [f"BOLs{i}" for i in range(1,41)]
col_cols = [f"COLs{i}" for i in range(1,41)]

col_p = COL["Output"]
bol_p = BOL["Output"]

bol_intra_regional = BOL[bol_cols]
bol_inter_regional = BOL[col_cols]

col_intra_regional = COL[col_cols]
col_inter_regional = COL[bol_cols]

# bol_intra_regional.head()




In [12]:
bol_intra_regional = BOL[bol_cols].to_numpy(na_value=0) #Matriz Z de Bolivia intra regional
bol_inter_regional = BOL[col_cols].to_numpy(na_value=0) #Matriz Z de Bolivia inter regional

col_intra_regional = COL[col_cols].to_numpy(na_value=0) #Matriz Z de Colombia intra regional
col_inter_regional = COL[bol_cols].to_numpy(na_value=0) #Matriz Z de Colombia inter regional

bol_P_unprocessed = bol_p.to_numpy(na_value=0)
col_P_unprocessed = col_p.to_numpy(na_value=0)

p1 = []
for i in bol_P_unprocessed:
    if i != 0:
        p1.append(i)
    else:
        p1.append(1)

p2 = []
for i in col_P_unprocessed:
    if i != 0:
        p2.append(i)
    else:
        p2.append(1)

bol_P = np.diag(p1)
col_P = np.diag(p2)	   

c)

In [ ]:
bol_intra_A = calcular_coeficientes_tecnicos(bol_intra_regional, bol_P)
bol_inter_A = calcular_coeficientes_tecnicos(bol_inter_regional, col_P)

col_intra_A = calcular_coeficientes_tecnicos(col_intra_regional, col_P)
col_inter_A = calcular_coeficientes_tecnicos(col_inter_regional, bol_P)


In [ ]:
rows, cols = bol_intra_A.shape
bol_intra_d = (np.eye(rows,cols) - bol_intra_A) @ bol_P
bol_inter_d = np.eye(rows,cols) - bol_inter_A

rows, cols = col_intra_A.shape
col_intra_d = np.eye(rows,cols)
col_inter_d = np.eye(rows,cols)


