# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1

##### Ecuacion
$$p = (I-A)^{-1}d = Ld$$

##### a. Cuando $ (I-A) $ es inversible la matriz de Leontief se puede calcular. En este caso la solucion al sistema 2 existe y es unica.

##### b. Cuando $ (I-A) $ es inversible pero el vector d = 0 tenemos una economia cerrada en donde para toda matriz de Leontief el valor de p va a ser 0.

##### c. Cuando $ (I-A) $ no es inversible significa que el sistema no tiene solucion unica o no tiene solucion.

##### d. Cuando $ (I-A) $ no es inversible y d = 0 el sistema se puede reducir a $ (I-A)p = 0 $ el cual posee soluciones no triviales por lo tanto hay soluciones infinitas que satisfacen la ecuacion.


### Consigna 2

In [2]:
from funciones import inversaLU, calcularPLU, solve_LU, calcularLU, inversaLUpivot, calcular_coeficientes_tecnicos
import numpy as np

---

### Consigna 3

In [5]:
A = np.array([[0.3, 0.0, 0.1],[0.05, 1.0, 0.2],[0.1, 0.15, 0.1]])
d = np.array([100,100,300])
rows,cols = A.shape
id = np.eye(rows, cols)
i_A = id - A
L, U, P= calcularPLU(i_A)
leontief = inversaLUpivot(L,U,P)

p = leontief @ d
p

array([   64.03940887, -5305.41871921,  -551.72413793])

a) Como el producto 2 necesita 1 producto 2 para producirse uno, ademas de los gastos de los demas productos nunca llega a satisfacer la demanda por ende so produccion total es negativa (creo que aca no estamos viendo bien a la matriz de la demanda interna la cual deberia ser la matriz de leontief y no la matriz A, lo que me llama la atencion es que nos esta viniendo con valores negativos cuando la demanda deberia ser positiva?)


---

### Consigna 4

In [3]:
delta_d = d + np.array([0,0,1])
delta_p = leontief @ delta_d
delta_p

array([   64.03940887, -5312.08538588,  -551.72413793])

---

### Consigna 5

In [4]:
Z = np.array([[350, 0, 0],[50, 250, 150],[200, 150, 550]])
rows, cols = Z.shape
P = np.array([[1000,0,0],[0,500,0],[0,0,1000]])

A = calcular_coeficientes_tecnicos(Z,P)
i_A = np.eye(rows, cols) - A
leontief = inversaLUpivot(*calcularPLU(i_A))
print(A)
leontief 

[[0.35 0.   0.  ]
 [0.05 0.5  0.15]
 [0.2  0.3  0.55]]


array([[1.53846154, 0.        , 0.        ],
       [0.44871795, 2.5       , 0.83333333],
       [0.98290598, 1.66666667, 2.77777778]])

---
### Consigna 6

"\n",
    "\n",
    "\n",
    "Lo que queremos lograr es deducir cómo varía la producción $p^r$ en función de una variación en la demanda, fijando el que no hay cambios en la demanda de la región $s$ (es decir, $\\Delta d^s = 0$). Vamos a descomponer el problema para deducir la fórmula $\\Delta p^r = (I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})^{-1}\\Delta d^r$.\n",
    "\n",
    "#### Empezamos a partir de la ecuación matricial de la fórmula 4\n",
    "\n",
    "$$\n",
    "\\left(\n",
    "\\begin{pmatrix}\n",
    "I_{n\\times n} & 0_{n\\times m} \\\\\n",
    "0_{m\\times n} & I_{m\\times m}\n",
    "\\end{pmatrix}\n",
    " -\n",
    "\\begin{pmatrix}\n",
    "A^{rr} & A^{rs} \\\\\n",
    "A^{sr} & A^{ss}\n",
    "\\end{pmatrix}\n",
    "\\right)\n",
    "\\begin{pmatrix}\n",
    "p^r \\\\\n",
    "p^s\n",
    "\\end{pmatrix} =\n",
    "\\begin{pmatrix}\n",
    "d^r \\\\\n",
    "d^s\n",
    "\\end{pmatrix}\n",
    "$$\n",
    "\n",
    "Descomponemos esta expresión en dos ecuaciones que corresponden a cada bloque:\n",
    "\n",
    "$$(I_{n\\times n} \\quad 0_{n\\times m}) - (A^{rr} \\quad A^{rs})\\begin{pmatrix}p^r \\\\ p^s\\end{pmatrix} = d^r$$\n",
    "\n",
    "$$(0_{m\\times n} \\quad I_{m\\times m}) - (A^{sr} \\quad A^{ss})\\begin{pmatrix}p^r \\\\ p^s\\end{pmatrix} = d^s$$\n",
    "\n",
    "Estas ecuaciones se pueden reescribir como:\n",
    "\n",
    "1. Para la región $r$:\n",
    "   $$(I - A^{rr})p^r - A^{rs}p^s = d^r$$\n",
    "\n",
    "2. Para la región $s$:\n",
    "   $$-A^{sr}p^r + (I - A^{ss})p^s = d^s$$\n",
    "\n",
    "\n",
    "\n",
    "####  Resolvemos la ecuación para $p^s$ y sustituimos $p^s$ en la ecuación de la región $r$\n",
    "\n",
    "Como sabemos que $\\Delta d^s = 0$  podemos resolver para $p^s$ en la segunda ecuación:\n",
    "\n",
    "$$(I - A^{ss})p^s = A^{sr}p^r$$\n",
    "\n",
    "Despejando $p^s$:\n",
    "\n",
    "$$p^s = (I - A^{ss})^{-1}A^{sr}p^r$$\n",
    "\n",
    "Ahora reemplazamos esta expresión de $p^s$ en la primera ecuación para la región $r$:\n",
    "\n",
    "$$(I - A^{rr})p^r - A^{rs}(I - A^{ss})^{-1}A^{sr}p^r = d^r$$\n",
    "\n",
    "Factorizamos $p^r$ en el lado izquierdo de la ecuación:\n",
    "\n",
    "$$(I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})p^r = d^r$$\n",
    "\n",
    "#### Variación de la demanda\n",
    "\n",
    "Si ahora consideramos una variación en la demanda $\\Delta d^r$, la ecuación queda:\n",
    "\n",
    "$$(I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})\\Delta p^r = \\Delta d^r$$\n",
    "\n",
    "Despejando $\\Delta p^r$, obtenemos la fórmula deseada:\n",
    "\n",
    "$$\\Delta p^r = (I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})^{-1}\\Delta d^r$$\n"






Lo que queremos lograr es deducir cómo varía la producción $p^r$ en función de una variación en la demanda, fijando el que no hay cambios en la demanda de la región $s$ (es decir, $\Delta d^s = 0$). Vamos a descomponer el problema para deducir la fórmula $\Delta p^r = (I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})^{-1}\Delta d^r$.

#### Empezamos a partir de la ecuación matricial de la fórmula 4

$$
\left(
\begin{pmatrix}
I_{n\times n} & 0_{n\times m} \\
0_{m\times n} & I_{m\times m}
\end{pmatrix}
 -
\begin{pmatrix}
A^{rr} & A^{rs} \\
A^{sr} & A^{ss}
\end{pmatrix}
\right)
\begin{pmatrix}
p^r \\
p^s
\end{pmatrix} =
\begin{pmatrix}
d^r \\
d^s
\end{pmatrix}
$$

Descomponemos esta expresión en dos ecuaciones que corresponden a cada bloque:

$$(I_{n\times n} \quad 0_{n\times m}) - (A^{rr} \quad A^{rs})\begin{pmatrix}p^r \\ p^s\end{pmatrix} = d^r$$

$$(0_{m\times n} \quad I_{m\times m}) - (A^{sr} \quad A^{ss})\begin{pmatrix}p^r \\ p^s\end{pmatrix} = d^s$$

Estas ecuaciones se pueden reescribir como:

1. Para la región $r$:
   $$(I - A^{rr})p^r - A^{rs}p^s = d^r$$

2. Para la región $s$:
   $$-A^{sr}p^r + (I - A^{ss})p^s = d^s$$



####  Resolvemos la ecuación para $p^s$ y sustituimos $p^s$ en la ecuación de la región $r$

Como sabemos que $\Delta d^s = 0$  podemos resolver para $p^s$ en la segunda ecuación:

$$(I - A^{ss})p^s = A^{sr}p^r$$

Despejando $p^s$:

$$p^s = (I - A^{ss})^{-1}A^{sr}p^r$$

Ahora reemplazamos esta expresión de $p^s$ en la primera ecuación para la región $r$:

$$(I - A^{rr})p^r - A^{rs}(I - A^{ss})^{-1}A^{sr}p^r = d^r$$

Factorizamos $p^r$ en el lado izquierdo de la ecuación:

$$(I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})p^r = d^r$$

#### Variación de la demanda

Si ahora consideramos una variación en la demanda $\Delta d^r$, la ecuación queda:

$$(I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})\Delta p^r = \Delta d^r$$

Despejando $\Delta p^r$, obtenemos la fórmula deseada:

$$\Delta p^r = (I - A^{rr} - A^{rs}(I - A^{ss})^{-1}A^{sr})^{-1}\Delta d^r$$


---
### Consigna 7

In [5]:
import pandas as pd

path = "matrizlatina2011_compressed_0.xlsx"
dataset = pd.read_excel(path, sheet_name=1)

b)

In [6]:

COL = dataset[dataset["Country_iso3"] =="COL"]
BOL = dataset[dataset["Country_iso3"] =="BOL"]

In [7]:
#Separamos los dataframes de cada pais 

bol_cols = [f"BOLs{i}" for i in range(1,41)]
col_cols = [f"COLs{i}" for i in range(1,41)]

col_p = COL["Output"]
bol_p = BOL["Output"]

bol_intra_regional = BOL[bol_cols]
bol_inter_regional = BOL[col_cols]

col_intra_regional = COL[col_cols]
col_inter_regional = COL[bol_cols]

# bol_intra_regional.head()




In [8]:
bol_intra_regional = BOL[bol_cols].to_numpy(na_value=0) #Matriz Z de Bolivia intra regional
bol_inter_regional = BOL[col_cols].to_numpy(na_value=0) #Matriz Z de Bolivia inter regional

col_intra_regional = COL[col_cols].to_numpy(na_value=0) #Matriz Z de Colombia intra regional
col_inter_regional = COL[bol_cols].to_numpy(na_value=0) #Matriz Z de Colombia inter regional

bol_P_vector = bol_p.to_numpy(na_value=0)
col_P_vector = col_p.to_numpy(na_value=0)

p1 = []
for i in bol_P_vector:
    if i != 0:
        p1.append(i)
    else:
        p1.append(1)

p2 = []
for i in col_P_vector:
    if i != 0:
        p2.append(i)
    else:
        p2.append(1)

bol_matriz_P = np.diag(p1)
col_matriz_P = np.diag(p2)	   

c)

In [9]:
bol_intra_A = calcular_coeficientes_tecnicos(bol_intra_regional, bol_matriz_P)
bol_inter_A = calcular_coeficientes_tecnicos(bol_inter_regional, col_matriz_P)

col_intra_A = calcular_coeficientes_tecnicos(col_intra_regional, col_matriz_P)
col_inter_A = calcular_coeficientes_tecnicos(col_inter_regional, bol_matriz_P)


In [10]:
rows, cols = bol_intra_A.shape
bol_d = (np.eye(rows,cols) - bol_intra_A) @ bol_P_vector - bol_inter_A @ col_P_vector



rows, cols = col_intra_A.shape
col_d = (np.eye(rows,cols) - col_intra_A) @ col_P_vector - col_inter_A @ bol_P_vector





In [11]:
#demanda Externa de Bolivia
bol_d

array([ 1.26608612e+03,  1.15933987e+00,  3.03254898e+03,  3.11747201e+03,
        1.06421612e+03,  6.82638584e+02,  2.87258137e+02,  1.14043661e+03,
        5.51613084e+02,  4.10833459e+01,  8.30981724e-01,  1.51702053e+02,
        6.97469056e+01,  3.10014524e+02,  1.84360782e+01,  5.02871264e+02,
       -1.99507449e+00,  6.89277255e+01,  1.09253860e+01,  4.36618726e+00,
        2.21155698e+02,  2.41008268e+00,  1.91381651e+02,  2.69310945e+01,
       -1.67018677e-01,  7.35725460e-02,  6.18439100e-02,  0.00000000e+00,
       -2.31823000e-04,  9.17380200e-02,  0.00000000e+00,  0.00000000e+00,
        6.28416338e+01,  3.35374044e+02,  1.64024755e+03,  1.44404812e+03,
        2.05230734e+02,  2.48139766e+02,  7.27063753e+01,  9.29991999e+03])

In [12]:
#demanda Externa de Colombia
col_d

array([1.25535963e+04, 3.84510479e+02, 3.14761594e+04, 1.14969110e+03,
       6.20601181e+03, 7.08221548e+03, 2.47530320e+03, 8.66425071e+03,
       4.10277950e+03, 2.90149501e+02, 1.16958658e+03, 5.88378063e+03,
       1.68285396e+03, 1.27391542e+02, 2.11474533e+03, 9.87656740e+03,
       2.25239056e+03, 3.82154916e+03, 1.75815579e+03, 1.39231561e+03,
       9.29809716e+02, 6.12048653e+02, 2.20212942e+03, 1.19095887e+03,
       1.59933825e+03, 4.09309481e+01, 7.35764351e+02, 1.73932175e+01,
       9.55901854e+01, 2.56524426e+03, 2.17495366e+02, 5.90423190e+02,
       2.73887773e+03, 6.15142023e+03, 4.75571262e+04, 1.45333189e+04,
       9.51589836e+03, 9.36538643e+03, 2.24437666e+03, 1.45834836e+05])

d)

In [13]:
bol_d[4] = bol_d[4] * 0.9
bol_d[5:8] = bol_d[5:8] * 1.033
delta_bol_d = bol_d

In [15]:
i_bol_A = np.eye(bol_intra_A.shape[0], bol_intra_A.shape[1]) - bol_intra_A
leontief_bol = inversaLUpivot(*calcularPLU(i_bol_A))
delta_bol_p = leontief_bol @ delta_bol_d
print(delta_bol_p)
print(bol_p)








[ 3.37511899e+03  4.01506676e+00  4.70909723e+03  3.63847686e+03
  1.14876742e+03  9.72419998e+02  3.71520267e+02  1.44190153e+03
  9.37721218e+02  5.42776266e+01  5.01839500e+01  1.95947620e+02
  2.05254280e+02  5.18592441e+02  1.82634517e+02  7.62314515e+02
 -1.42808604e+00  1.28191057e+02  5.95149408e+01  9.29078531e+01
  7.78053024e+02  5.53505546e+00  4.08288357e+02  4.10110062e+01
  8.92505556e+00  6.29437953e-01  1.15514871e+01  0.00000000e+00
 -2.31823000e-04  7.63149425e+00  0.00000000e+00  0.00000000e+00
  8.92448630e+01  6.42572800e+02  1.68455182e+03  3.27050837e+03
  4.77968409e+02  4.67601123e+02  6.83038643e+02  1.02165355e+04]
80      3487.321711
81         4.048915
82      4716.747980
83      3646.153101
84      1265.894610
85       945.641845
86       364.425893
87      1574.674025
88       982.678047
89        54.277627
90        52.205045
91       223.845643
92       206.825080
93       518.992799
94       183.592177
95       764.427372
96        -1.203619
97       